<a href="https://colab.research.google.com/github/ashbornarise/Machine-Learning-research/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/ashbornarise/Machine-Learning-research.git

In [3]:
print(" I'm exited today to learn pytorch")

 I'm exited today to learn pytorch


In [4]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [5]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [6]:
## Introduction to Tensors
### Creating tensors

In [7]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [8]:
scalar.ndim

0

In [9]:
#Get tensor back as python int
scalar.item()

7

In [10]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [11]:
vector.ndim

1

In [12]:
vector.shape

torch.Size([2])

In [13]:
#Create a matrix
MATRIX = torch.tensor([[7,8],
                       [9,20]])
MATRIX

tensor([[ 7,  8],
        [ 9, 20]])

In [14]:
MATRIX.ndim

2

In [15]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 20])

In [16]:
MATRIX.shape

torch.Size([2, 2])

In [17]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
TENSOR.ndim

3

In [19]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tensors


In [21]:
### Random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7722, 0.1653, 0.9491, 0.5311],
        [0.9165, 0.6651, 0.6934, 0.6890],
        [0.5349, 0.0554, 0.7600, 0.1623]])

In [22]:
random_tensor.ndim

2

In [23]:
random_image_size_Tensor = torch.rand(size = (3, 224, 224))
random_image_size_Tensor.shape, random_image_size_Tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeroes and ones

In [24]:
torch.rand(3,3)

tensor([[0.0803, 0.3460, 0.8020],
        [0.1402, 0.0100, 0.1533],
        [0.8195, 0.7103, 0.3568]])

In [25]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [27]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [28]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [29]:
one_to_ten = torch.arange(start =1,end =11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensors datatypes

In [31]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [32]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.5876, 0.3796, 0.3287, 0.0034],
        [0.7696, 0.9549, 0.6617, 0.9137],
        [0.1545, 0.0282, 0.7294, 0.6409]])

In [33]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [34]:
some_tensor.size()

torch.Size([3, 4])

In [36]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5876, 0.3796, 0.3287, 0.0034],
        [0.7696, 0.9549, 0.6617, 0.9137],
        [0.1545, 0.0282, 0.7294, 0.6409]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x7f698668a750>
Device tensor is on: cpu


Manipulation Tensors(tensor operations)

In [39]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [40]:
tensor * 10

tensor([10, 20, 30])

In [41]:
tensor - 10

tensor([-9, -8, -7])

In [42]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [45]:
torch.add(tensor, 10)

tensor([11, 12, 13])

Multiplication with a tensor

In [46]:
tensor * tensor

tensor([1, 4, 9])

In [48]:
print(tensor, "*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [49]:
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 3.21 ms, sys: 0 ns, total: 3.21 ms
Wall time: 3.37 ms
