<a href="https://colab.research.google.com/github/ashbornarise/Machine-Learning-research/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/ashbornarise/Machine-Learning-research.git

In [1]:
print(" I'm exited today to learn pytorch")

 I'm exited today to learn pytorch


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [4]:
## Introduction to Tensors
### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [ ]:
#Get tensor back as python int
scalar.item()

In [7]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [13]:
#Create a matrix
MATRIX = torch.tensor([[7,8],
                       [9,20]])
MATRIX

tensor([[ 7,  8],
        [ 9, 20]])

In [14]:
MATRIX.ndim

2

In [16]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 20])

In [17]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [19]:
TENSOR.ndim

3

In [20]:
TENSOR.shape

torch.Size([1, 3, 3])

In [21]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tensors


In [28]:
### Random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.1325, 0.2299, 0.7268, 0.2824],
        [0.0716, 0.1407, 0.0256, 0.8486],
        [0.8774, 0.8708, 0.8772, 0.0614]])

In [29]:
random_tensor.ndim

2

In [33]:
random_image_size_Tensor = torch.rand(size = (3, 224, 224))
random_image_size_Tensor.shape, random_image_size_Tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeroes and ones

In [34]:
torch.rand(3,3)

tensor([[0.3816, 0.5988, 0.6741],
        [0.6766, 0.7075, 0.3360],
        [0.1350, 0.7910, 0.4901]])

In [36]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [37]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [38]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [39]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [44]:
one_to_ten = torch.arange(start =1,end =11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [45]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensors datatypes

In [47]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])