<a href="https://colab.research.google.com/github/ashbornarise/Machine-Learning-research/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://github.com/ashbornarise/Machine-Learning-research.git

In [1]:
print(" I'm exited today to learn pytorch")

 I'm exited today to learn pytorch


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


In [4]:
## Introduction to Tensors
### Creating tensors

In [5]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
#Get tensor back as python int
scalar.item()

7

In [8]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [11]:
#Create a matrix
MATRIX = torch.tensor([[7,8],
                       [9,20]])
MATRIX

tensor([[ 7,  8],
        [ 9, 20]])

In [12]:
MATRIX.ndim

2

In [13]:
MATRIX[0]
MATRIX[1]

tensor([ 9, 20])

In [14]:
MATRIX.shape

torch.Size([2, 2])

In [15]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [16]:
TENSOR.ndim

3

In [17]:
TENSOR.shape

torch.Size([1, 3, 3])

In [18]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

Random Tensors


In [19]:
### Random tensors
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.7497, 0.7847, 0.5092, 0.6246],
        [0.5779, 0.0390, 0.6545, 0.6645],
        [0.9038, 0.7030, 0.5032, 0.3316]])

In [20]:
random_tensor.ndim

2

In [21]:
random_image_size_Tensor = torch.rand(size = (3, 224, 224))
random_image_size_Tensor.shape, random_image_size_Tensor.ndim

(torch.Size([3, 224, 224]), 3)

Zeroes and ones

In [22]:
torch.rand(3,3)

tensor([[0.5431, 0.6604, 0.1468],
        [0.7130, 0.2508, 0.9331],
        [0.2820, 0.1795, 0.2596]])

In [23]:
zeros = torch.zeros(size = (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [24]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [25]:
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [26]:
ones.dtype

torch.float32

Creating a range of tensors and tensors-like

In [27]:
one_to_ten = torch.arange(start =1,end =11, step=1)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensors datatypes

In [29]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad = False)
float_32_tensor

tensor([3., 6., 9.])

In [30]:
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.9342, 0.9510, 0.8876, 0.4113],
        [0.9233, 0.5475, 0.0414, 0.2338],
        [0.1769, 0.0246, 0.3795, 0.6015]])

In [31]:
some_tensor.size, some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [32]:
some_tensor.size()

torch.Size([3, 4])

In [33]:
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.size}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.9342, 0.9510, 0.8876, 0.4113],
        [0.9233, 0.5475, 0.0414, 0.2338],
        [0.1769, 0.0246, 0.3795, 0.6015]])
Datatype of tensor: torch.float32
Shape of tensor: <built-in method size of Tensor object at 0x7fcd369e8290>
Device tensor is on: cpu


Manipulation Tensors(tensor operations)

In [34]:
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [35]:
tensor * 10

tensor([10, 20, 30])

In [36]:
tensor - 10

tensor([-9, -8, -7])

In [37]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [38]:
torch.add(tensor, 10)

tensor([11, 12, 13])

Multiplication with a tensor

In [39]:
tensor * tensor

tensor([1, 4, 9])

In [40]:
print(tensor, "*", tensor)
print(f"Equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [41]:
torch.matmul(tensor, tensor)

tensor(14)

In [42]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

print(value)

tensor(14)
CPU times: user 1.76 ms, sys: 0 ns, total: 1.76 ms
Wall time: 3.19 ms


In [43]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 9],
                         [8, 11],
                         [9, 12]])

print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}(Same shape as above),tensor_B.T = {tensor_B.T.shape}")
print(f"Multipliying:{tensor_A.shape} @ {tensor_B.T.shape}<- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2])(Same shape as above),tensor_B.T = torch.Size([2, 3])
Multipliying:torch.Size([3, 2]) @ torch.Size([2, 3])<- inner dimensions must match
Output:

tensor([[ 25,  30,  33],
        [ 57,  68,  75],
        [ 89, 106, 117]])

Output shape: torch.Size([3, 3])


In [44]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [45]:
tensor_B.T

tensor([[ 7,  8,  9],
        [ 9, 11, 12]])

Finding min, max, mean, sum, etc(tensor Agrregation)

In [46]:
x = torch.arange(0, 100, 10)
x
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [47]:
torch.min(x), x.min()


(tensor(0), tensor(0))

In [48]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [49]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [50]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [51]:
x.argmin()

tensor(0)

In [52]:
x.argmax()

tensor(9)

Reshaping, stacking, sqeezing and unsquezing tensors

In [53]:
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [54]:
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [55]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [56]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [57]:
x_stacked = torch.stack([x, x, x, x], dim = 0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [58]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [59]:
print(f"Previous target: {x_reshaped.squeeze()}")
print(f"Previous shape: {x_reshaped.squeeze().shape}")


x_unsqueezed = x_reshaped.squeeze().unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [60]:
x_original = torch.rand(size = (224, 224, 3))

x_permuted = x_original.permute(2, 0, 1)

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [61]:
x_original[0, 0, 0], x_permuted[0, 0, 0]

(tensor(0.7915), tensor(0.7915))

Indexing(Selecting Data from tensors)


In [62]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [63]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [64]:
x[0][0]

tensor([1, 2, 3])

In [65]:
x[0][1][1]

tensor(5)

In [66]:
x[:, 0]

tensor([[1, 2, 3]])

In [67]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [68]:
x[0, 0, :]

tensor([1, 2, 3])

Pytorch and Numpy

In [69]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [70]:
array.dtype

dtype('float64')

In [71]:
torch.arange(1.0, 8.0).dtype

torch.float32

In [72]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [73]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [1]:
import torch

random_tensor_A  = torch.rand(3, 4)
random_tensor_B  = torch.rand(3, 4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

torch.rand(3, 3)

tensor([[0.0839, 0.4411, 0.9149, 0.3164],
        [0.6863, 0.1630, 0.8880, 0.8520],
        [0.4963, 0.9302, 0.6964, 0.3730]])
tensor([[0.3054, 0.6475, 0.6290, 0.2859],
        [0.7142, 0.1151, 0.9209, 0.9762],
        [0.3897, 0.7422, 0.4061, 0.2614]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


tensor([[0.2736, 0.3593, 0.4236],
        [0.7302, 0.8827, 0.6930],
        [0.2602, 0.4367, 0.2868]])

In [5]:
import torch

RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])
